name: qa-playwright

on:
  workflow_dispatch:
    inputs:
      base-url:
        description: 'Base URL of the deployment under test (defaults to QA_BASE_URL secret)'
        required: false
      admin-email:
        description: 'Admin login email override (defaults to QA_ADMIN_EMAIL secret)'
        required: false
      admin-password:
        description: 'Admin login password override (defaults to QA_ADMIN_PASSWORD secret)'
        required: false
  schedule:
    - cron: '0 5 * * *'

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BASE_URL: ${{ inputs.base-url != '' && inputs.base-url || secrets.QA_BASE_URL }}
      PLAYWRIGHT_ADMIN_EMAIL: ${{ inputs.admin-email != '' && inputs.admin-email || secrets.QA_ADMIN_EMAIL }}
      PLAYWRIGHT_ADMIN_PASSWORD: ${{ inputs.admin-password != '' && inputs.admin-password || secrets.QA_ADMIN_PASSWORD }}
      PLAYWRIGHT_START_SERVER: 'false'
    steps:
      - name: Check required configuration
        run: |
          if [ -z "$PLAYWRIGHT_BASE_URL" ]; then
            echo "PLAYWRIGHT_BASE_URL is required. Provide it as an input or set QA_BASE_URL secret." >&2
            exit 1
          fi
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright suite
        run: npm run test:e2e
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
