name: vercel-deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: vercel-deploy-main
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build & deploy via Vercel CLI
        id: vercel
        uses: ./.github/actions/vercel-cli-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-team-id: ${{ secrets.VERCEL_TEAM_ID }}

      - name: Echo deploy URL
        run: |
          echo "Deployed: ${{ steps.vercel.outputs.url }}"
